apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: registry.cn-hangzhou.aliyuncs.com/fishgo/webserver:1.0
        resources:
          requests:
            cpu: 250m
            memory: 512m
---
apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
